WIDTH = 100
HEIGHT = 100

POPULATION_SIZE = 100
NUMBER_OF_GENERATIONS = 1

GENOME_LENGTH = 4
MAX_NUMBER_OF_INNER_NEURONS = 5

LONG_PROBE_DISTANCE = None

KILL_ENABLED = False

STEPS_PER_GENERATION = 30

RESPONSIVENESS_CURVE_K_FACTOR = 2

NEIGHBOURHOOD_RADIUS = 3