import os.path

PATH_TO_ROOT = os.path.join(os.path.expanduser('~'), 'Documents')

ROOT_FOLDER_NAME = 'evolution'

SAVES_FOLDER_NAME = 'saves'
SETTINGS_FILE_NAME = 'settings.json'

ROOT_FOLDER_PATH = os.path.join(PATH_TO_ROOT, ROOT_FOLDER_NAME)

SAVES_FOLDER_PATH = os.path.join(ROOT_FOLDER_PATH, SAVES_FOLDER_NAME)
SETTINGS_PATH = os.path.join(ROOT_FOLDER_PATH, SETTINGS_FILE_NAME)

## saving simulation ##
SAVE_ANIMATION = True
SAVE_EVOLUTION_STEP = True
SAVE_GENERATION = True
SAVE_SELECTION = True
SAVE_POPULATION = True
SAVE_GRID = True
SAVE_CONFIG = True
SAVE = SAVE_EVOLUTION_STEP or SAVE_GENERATION or SAVE_SELECTION or SAVE_POPULATION or SAVE_GRID or SAVE_CONFIG

SAVE_FOLDER = "saved"
